### ISSUE TITLE
Please investigate non-compliant route

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#105] opened 2020-03-19 17:54 UTC
Non-compliant route - 68 Ave and 184 Street are not designated truck routes

![image](https://user-images.githubusercontent.com/59627982/77098596-d91e2680-69cf-11ea-9731-3dc2f032f985.png)

**Comment by gk-tl** [comment] 2020-03-19 18:01
Non-compliant route - 64 Ave between 192 Street and Fraser Highway is not a designated truck route.

![image](https://user-images.githubusercontent.com/59627982/77099199-cc4e0280-69d0-11ea-9c1e-e1f2c4aaa106.png)

**Comment by mraross** [comment] 2020-03-19 18:40
Looks fine in next version of router/data:

![image](https://user-images.githubusercontent.com/11318574/77102660-6a909700-69d6-11ea-9b6c-639d4e4f795d.png)

**Comment by gk-tl** [comment] 2020-03-19 18:50
Thanks Michael. 

Please note: 64 Ave between 192 Street and Fraser Highway is showing as a truck route.

![image](https://user-images.githubusercontent.com/59627982/77103478-b1cb5780-69d7-11ea-8015-1329b26ca591.png)

**Comment by gleeming** [comment] 2020-03-19 19:52
I have confirmed that Translink did not designate that section of 64 Ave as truck route in their data and Refractions did not reconcile and submit it to GeoBC as part of the bulk update at the end of January.  However in the February ITN release this section was tagged as a truck route.

I have reviewed a file of the proposed additions that Joy was manually cleaning up at the time (due to splits/retirements at the same time as the reconciliation).  For some reason this 64 Ave section appears to have been added in during those edits.  I will ticket those segments for undesignating.  No other cases elsewhere in that file involved net-new areas.  Hopefully that matches with the edits they actually committed, i.e. just this one problem introduced.

**Comment by gk-tl** [comment] 2020-03-19 20:31
Thanks Graeme. Thanks Michael. 

In case you're wondering about the underlying cause for this stub (our technical term is "dangler") - 192 Street is the boundary between Township of Langley and City of Surrey.  64 Ave is a designate truck route in Langley, but not Surrey.  This is one of the many quirks of the TRN in the Lower Mainland :-)

Please note the other non-compliant route.

![image](https://user-images.githubusercontent.com/59627982/77112027-894a5a00-69e5-11ea-8e91-9841d1f6729e.png)

**Comment by gleeming** [comment] 2020-03-19 20:38
The other non-compliant case doesn't route like that for me when a multiplier is set.  It takes 56 Ave east to Langley Bypass and then back northwest along Fraser Hwy.  It remains on the truck route the whole way except for right at the origin.

**Comment by gk-tl** [comment] 2020-03-19 20:41
I tried it again to double check. Here's what I get using https://bcgov.github.io/smk-tlink/?config=./config/test-services.json

![image](https://user-images.githubusercontent.com/59627982/77112994-3d001980-69e7-11ea-8e33-bed4b5e93c46.png)

**Comment by mraross** [comment] 2020-03-20 19:11
Looking good in latest version of Router API:

49.10330,-122.74132
7480 176 St, Surrey, BC

![image](https://user-images.githubusercontent.com/11318574/77198173-b3625180-6aa3-11ea-9f67-b12ceb513542.png)

**Comment by gk-tl** [comment] 2020-03-20 19:37
Thank you Michael. Looks good.

**Comment by gk-tl** [comment] 2020-03-20 19:47
This would also be a valid route (i.e., router is behaving as expected).

![image](https://user-images.githubusercontent.com/59627982/77200931-d17e8080-6aa8-11ea-932f-fdc676274ac3.png)


![image](https://user-images.githubusercontent.com/59627982/77200887-b6137580-6aa8-11ea-8b9f-6d2c83a5bc5a.png)

**Comment by NicoledeGreef** [comment] 2020-03-25 18:44
closing this issue as we are expecting the fix to come in with the latest router.

**Closed by NicoledeGreef** 2020-03-25 18:44 UTC
Labels: Omega

**Comment by gk-tl** [comment] 2020-03-25 19:16
Thank you.
