### ISSUE TITLE
Dev app freezing

### ISSUE THREAD

**Issue by al-tabb** [bcgov/smk-tlink#247] opened 2022-09-12 22:29 UTC
The dev application (https://translink-d.apps.gov.bc.ca/trp/) has been freezing up consistently for me.  This occurs both when using Chrome and Edge.

![image](https://user-images.githubusercontent.com/59742145/189769620-cc699f3b-94e7-418b-b705-53fc1214daf1.png)

**Comment by dgboss** [comment] 2022-09-12 22:41
@al-tabb Michael and I were working on some updates to the deployment process in the dev environment. We triggered a number of builds from 2:30-3:30pm. Does this coincide with the timing of the problem you were observing? Our updates are complete; hopefully the issue has been resolved.

**Comment by al-tabb** [comment] 2022-09-12 22:43
I've actually been noticing this issue for the past few weeks.  To provide a bit more detail, the app freezes for me consistently when attempting to use the identify tool.

**Comment by NicoledeGreef** [comment] 2022-09-12 23:20
Hi @al-tabb,  Could you please try an incognito (Chrome) or InPrivate (Edge) window and see if you experience the same issue?

**Comment by al-tabb** [comment] 2022-09-12 23:28
I get the same issue when using incognito mode.

**Comment by NicoledeGreef** [comment] 2022-09-13 23:31
I also have this issue during Identify currently.  However, the dev environment is a deployment of code in progress.  Not ready for review/testing just yet :)

**Comment by dgboss** [comment] 2022-09-14 17:38
I've 'identified' (sorry) the root cause and have a fix for it. I hope to have the fix deployed to the dev environment by early next week.

**Comment by dgboss** [comment] 2022-09-14 22:53
The fix has been merged into the dev application. Please let us know if this doesn't resolve the issue for you (you may need to clear your browser's cache).

**Comment by NicoledeGreef** [comment] 2022-09-15 17:09
Identify is working better for me now - thanks!

**Comment by al-tabb** [comment] 2022-09-20 17:40
The identify tool is now working well for me in dev.  Thanks.

**Comment by dgboss** [comment] 2022-09-20 17:45
Thanks for the confirmation. I'll go ahead and close this issue.

**Closed by dgboss** 2022-09-20 17:45 UTC
Labels: bug
